---
- name: Install common packages
  ansible.builtin.dnf:
    name:
      - vim
      - curl
      - wget
      - net-tools
      - bash-completion
    state: present

- name: Ensure firewalld is running
  ansible.builtin.service:
    service: http
    permanent: true
    state: enabled
    immediate: yes
