---
 - name: Install httpd
   ansible.builtin.dnf:
     name: httpd
     state: present

 - name: Start and enable httpd
   ansible.builtin.service:
     name: httpd
     state: started
     enabled: true
   notify: Restart httpd

 - name: Open firewall for http
   ansible.builtin.service:
     service: http
     permanent: true
     state: enabled
     immediate: true

 - name: Deploy index page
   ansible.builtin.template:
     src: index.html.j2
     dest: /var/www/html/index.html
   notify: Restart httpd
